version: '3.8'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ilbbtasf-12345
      POSTGRES_DB: blogapp_development
      SECRET_KEY_BASE: 1673cb4d8582017563eca5d4ab069ef2f18b03e5630555dddb91b6d8b4a57a8d0542143fa1d3c698fdfd83b0898ab3282a36cfa6826d8f70cc9662d59ecbc445
      JWT_SECRET_KEY: this is my secret key

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: 1673cb4d8582017563eca5d4ab069ef2f18b03e5630555dddb91b6d8b4a57a8d0542143fa1d3c698fdfd83b0898ab3282a36cfa6826d8f70cc9662d59ecbc445
      JWT_SECRET_KEY: this is my secret key
 

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: 498cdc053dd20636474e2ee4ec52351f
      SECRET_KEY_BASE: 1673cb4d8582017563eca5d4ab069ef2f18b03e5630555dddb91b6d8b4a57a8d0542143fa1d3c698fdfd83b0898ab3282a36cfa6826d8f70cc9662d59ecbc445
      JWT_SECRET_KEY: this is my secret key

volumes:
  postgres_data:
  redis_data:
