# aws:
#   access_key_id: 123
#   secret_access_key: 345
devise:
  jwt_secret_key: this is my secret key
# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 1673cb4d8582017563eca5d4ab069ef2f18b03e5630555dddb91b6d8b4a57a8d0542143fa1d3c698fdfd83b0898ab3282a36cfa6826d8f70cc9662d59ecbc445
